from setuptools import setup

setup(
    name='HFS2018',
    version='0.1',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip._vendor', 'venv.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip._internal', 'venv.lib.python2.7.site-packages.pip._internal.req',
              'venv.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.lib.python2.7.site-packages.pip._internal.utils',
              'venv.lib.python2.7.site-packages.pip._internal.models',
              'venv.lib.python2.7.site-packages.pip._internal.commands',
              'venv.lib.python2.7.site-packages.pip._internal.operations', 'venv.lib.python2.7.site-packages.pytz',
              'venv.lib.python2.7.site-packages.click', 'venv.lib.python2.7.site-packages.flask',
              'venv.lib.python2.7.site-packages.flask.ext', 'venv.lib.python2.7.site-packages.numpy',
              'venv.lib.python2.7.site-packages.numpy.ma', 'venv.lib.python2.7.site-packages.numpy.ma.tests',
              'venv.lib.python2.7.site-packages.numpy.doc', 'venv.lib.python2.7.site-packages.numpy.fft',
              'venv.lib.python2.7.site-packages.numpy.fft.tests', 'venv.lib.python2.7.site-packages.numpy.lib',
              'venv.lib.python2.7.site-packages.numpy.lib.tests', 'venv.lib.python2.7.site-packages.numpy.core',
              'venv.lib.python2.7.site-packages.numpy.core.tests', 'venv.lib.python2.7.site-packages.numpy.f2py',
              'venv.lib.python2.7.site-packages.numpy.f2py.tests', 'venv.lib.python2.7.site-packages.numpy.tests',
              'venv.lib.python2.7.site-packages.numpy.compat', 'venv.lib.python2.7.site-packages.numpy.linalg',
              'venv.lib.python2.7.site-packages.numpy.linalg.tests', 'venv.lib.python2.7.site-packages.numpy.random',
              'venv.lib.python2.7.site-packages.numpy.random.tests', 'venv.lib.python2.7.site-packages.numpy.testing',
              'venv.lib.python2.7.site-packages.numpy.testing.tests',
              'venv.lib.python2.7.site-packages.numpy.testing.nose_tools',
              'venv.lib.python2.7.site-packages.numpy.distutils',
              'venv.lib.python2.7.site-packages.numpy.distutils.tests',
              'venv.lib.python2.7.site-packages.numpy.distutils.command',
              'venv.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python2.7.site-packages.numpy.matrixlib',
              'venv.lib.python2.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python2.7.site-packages.numpy.polynomial',
              'venv.lib.python2.7.site-packages.numpy.polynomial.tests', 'venv.lib.python2.7.site-packages.scipy',
              'venv.lib.python2.7.site-packages.scipy.io', 'venv.lib.python2.7.site-packages.scipy.io.arff',
              'venv.lib.python2.7.site-packages.scipy.io.arff.tests', 'venv.lib.python2.7.site-packages.scipy.io.tests',
              'venv.lib.python2.7.site-packages.scipy.io.matlab',
              'venv.lib.python2.7.site-packages.scipy.io.matlab.tests',
              'venv.lib.python2.7.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python2.7.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python2.7.site-packages.scipy.odr', 'venv.lib.python2.7.site-packages.scipy.odr.tests',
              'venv.lib.python2.7.site-packages.scipy._lib', 'venv.lib.python2.7.site-packages.scipy._lib.tests',
              'venv.lib.python2.7.site-packages.scipy.misc', 'venv.lib.python2.7.site-packages.scipy.misc.tests',
              'venv.lib.python2.7.site-packages.scipy.stats', 'venv.lib.python2.7.site-packages.scipy.stats.tests',
              'venv.lib.python2.7.site-packages.scipy.linalg', 'venv.lib.python2.7.site-packages.scipy.linalg.tests',
              'venv.lib.python2.7.site-packages.scipy.signal', 'venv.lib.python2.7.site-packages.scipy.signal.tests',
              'venv.lib.python2.7.site-packages.scipy.sparse', 'venv.lib.python2.7.site-packages.scipy.sparse.tests',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python2.7.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python2.7.site-packages.scipy.sparse.csgraph',
              'venv.lib.python2.7.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python2.7.site-packages.scipy.cluster', 'venv.lib.python2.7.site-packages.scipy.cluster.tests',
              'venv.lib.python2.7.site-packages.scipy.fftpack', 'venv.lib.python2.7.site-packages.scipy.fftpack.tests',
              'venv.lib.python2.7.site-packages.scipy.ndimage', 'venv.lib.python2.7.site-packages.scipy.ndimage.tests',
              'venv.lib.python2.7.site-packages.scipy.spatial', 'venv.lib.python2.7.site-packages.scipy.spatial.tests',
              'venv.lib.python2.7.site-packages.scipy.special', 'venv.lib.python2.7.site-packages.scipy.special.tests',
              'venv.lib.python2.7.site-packages.scipy.special._precompute',
              'venv.lib.python2.7.site-packages.scipy.optimize', 'venv.lib.python2.7.site-packages.scipy.optimize._lsq',
              'venv.lib.python2.7.site-packages.scipy.optimize.tests',
              'venv.lib.python2.7.site-packages.scipy.optimize._trlib',
              'venv.lib.python2.7.site-packages.scipy.constants',
              'venv.lib.python2.7.site-packages.scipy.constants.tests',
              'venv.lib.python2.7.site-packages.scipy.integrate',
              'venv.lib.python2.7.site-packages.scipy.integrate._ivp',
              'venv.lib.python2.7.site-packages.scipy.integrate.tests',
              'venv.lib.python2.7.site-packages.scipy.interpolate',
              'venv.lib.python2.7.site-packages.scipy.interpolate.tests',
              'venv.lib.python2.7.site-packages.scipy._build_utils', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
              'venv.lib.python2.7.site-packages.jinja2', 'venv.lib.python2.7.site-packages.pandas',
              'venv.lib.python2.7.site-packages.pandas.io', 'venv.lib.python2.7.site-packages.pandas.io.sas',
              'venv.lib.python2.7.site-packages.pandas.io.json', 'venv.lib.python2.7.site-packages.pandas.io.formats',
              'venv.lib.python2.7.site-packages.pandas.io.msgpack',
              'venv.lib.python2.7.site-packages.pandas.io.clipboard', 'venv.lib.python2.7.site-packages.pandas.api',
              'venv.lib.python2.7.site-packages.pandas.api.types', 'venv.lib.python2.7.site-packages.pandas.core',
              'venv.lib.python2.7.site-packages.pandas.core.util', 'venv.lib.python2.7.site-packages.pandas.core.tools',
              'venv.lib.python2.7.site-packages.pandas.core.dtypes',
              'venv.lib.python2.7.site-packages.pandas.core.sparse',
              'venv.lib.python2.7.site-packages.pandas.core.indexes',
              'venv.lib.python2.7.site-packages.pandas.core.reshape',
              'venv.lib.python2.7.site-packages.pandas.core.computation',
              'venv.lib.python2.7.site-packages.pandas.util', 'venv.lib.python2.7.site-packages.pandas._libs',
              'venv.lib.python2.7.site-packages.pandas._libs.tslibs', 'venv.lib.python2.7.site-packages.pandas.stats',
              'venv.lib.python2.7.site-packages.pandas.tests', 'venv.lib.python2.7.site-packages.pandas.tests.io',
              'venv.lib.python2.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python2.7.site-packages.pandas.tests.io.json',
              'venv.lib.python2.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python2.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python2.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python2.7.site-packages.pandas.tests.api', 'venv.lib.python2.7.site-packages.pandas.tests.util',
              'venv.lib.python2.7.site-packages.pandas.tests.frame',
              'venv.lib.python2.7.site-packages.pandas.tests.tools',
              'venv.lib.python2.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python2.7.site-packages.pandas.tests.scalar',
              'venv.lib.python2.7.site-packages.pandas.tests.series',
              'venv.lib.python2.7.site-packages.pandas.tests.sparse',
              'venv.lib.python2.7.site-packages.pandas.tests.groupby',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python2.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python2.7.site-packages.pandas.tests.reshape',
              'venv.lib.python2.7.site-packages.pandas.tests.tseries',
              'venv.lib.python2.7.site-packages.pandas.tests.indexing',
              'venv.lib.python2.7.site-packages.pandas.tests.plotting',
              'venv.lib.python2.7.site-packages.pandas.tests.internals',
              'venv.lib.python2.7.site-packages.pandas.tests.computation',
              'venv.lib.python2.7.site-packages.pandas.tools', 'venv.lib.python2.7.site-packages.pandas.types',
              'venv.lib.python2.7.site-packages.pandas.compat', 'venv.lib.python2.7.site-packages.pandas.compat.numpy',
              'venv.lib.python2.7.site-packages.pandas.errors', 'venv.lib.python2.7.site-packages.pandas.formats',
              'venv.lib.python2.7.site-packages.pandas.tseries', 'venv.lib.python2.7.site-packages.pandas.plotting',
              'venv.lib.python2.7.site-packages.pandas.computation', 'venv.lib.python2.7.site-packages.sklearn',
              'venv.lib.python2.7.site-packages.sklearn.svm', 'venv.lib.python2.7.site-packages.sklearn.svm.tests',
              'venv.lib.python2.7.site-packages.sklearn.tree', 'venv.lib.python2.7.site-packages.sklearn.tree.tests',
              'venv.lib.python2.7.site-packages.sklearn.tests', 'venv.lib.python2.7.site-packages.sklearn.utils',
              'venv.lib.python2.7.site-packages.sklearn.utils.tests',
              'venv.lib.python2.7.site-packages.sklearn.utils.sparsetools',
              'venv.lib.python2.7.site-packages.sklearn.utils.sparsetools.tests',
              'venv.lib.python2.7.site-packages.sklearn.cluster',
              'venv.lib.python2.7.site-packages.sklearn.cluster.tests',
              'venv.lib.python2.7.site-packages.sklearn.metrics',
              'venv.lib.python2.7.site-packages.sklearn.metrics.tests',
              'venv.lib.python2.7.site-packages.sklearn.metrics.cluster',
              'venv.lib.python2.7.site-packages.sklearn.metrics.cluster.tests',
              'venv.lib.python2.7.site-packages.sklearn.mixture',
              'venv.lib.python2.7.site-packages.sklearn.mixture.tests',
              'venv.lib.python2.7.site-packages.sklearn.datasets',
              'venv.lib.python2.7.site-packages.sklearn.datasets.tests',
              'venv.lib.python2.7.site-packages.sklearn.ensemble',
              'venv.lib.python2.7.site-packages.sklearn.ensemble.tests',
              'venv.lib.python2.7.site-packages.sklearn.manifold',
              'venv.lib.python2.7.site-packages.sklearn.manifold.tests',
              'venv.lib.python2.7.site-packages.sklearn.externals',
              'venv.lib.python2.7.site-packages.sklearn.externals.joblib',
              'venv.lib.python2.7.site-packages.sklearn.neighbors',
              'venv.lib.python2.7.site-packages.sklearn.neighbors.tests',
              'venv.lib.python2.7.site-packages.sklearn.covariance',
              'venv.lib.python2.7.site-packages.sklearn.covariance.tests',
              'venv.lib.python2.7.site-packages.sklearn._build_utils',
              'venv.lib.python2.7.site-packages.sklearn.linear_model',
              'venv.lib.python2.7.site-packages.sklearn.linear_model.tests',
              'venv.lib.python2.7.site-packages.sklearn.__check_build',
              'venv.lib.python2.7.site-packages.sklearn.decomposition',
              'venv.lib.python2.7.site-packages.sklearn.decomposition.tests',
              'venv.lib.python2.7.site-packages.sklearn.preprocessing',
              'venv.lib.python2.7.site-packages.sklearn.preprocessing.tests',
              'venv.lib.python2.7.site-packages.sklearn.neural_network',
              'venv.lib.python2.7.site-packages.sklearn.neural_network.tests',
              'venv.lib.python2.7.site-packages.sklearn.model_selection',
              'venv.lib.python2.7.site-packages.sklearn.model_selection.tests',
              'venv.lib.python2.7.site-packages.sklearn.semi_supervised',
              'venv.lib.python2.7.site-packages.sklearn.semi_supervised.tests',
              'venv.lib.python2.7.site-packages.sklearn.gaussian_process',
              'venv.lib.python2.7.site-packages.sklearn.gaussian_process.tests',
              'venv.lib.python2.7.site-packages.sklearn.feature_selection',
              'venv.lib.python2.7.site-packages.sklearn.feature_selection.tests',
              'venv.lib.python2.7.site-packages.sklearn.feature_extraction',
              'venv.lib.python2.7.site-packages.sklearn.feature_extraction.tests',
              'venv.lib.python2.7.site-packages.sklearn.cross_decomposition',
              'venv.lib.python2.7.site-packages.sklearn.cross_decomposition.tests',
              'venv.lib.python2.7.site-packages.dateutil', 'venv.lib.python2.7.site-packages.dateutil.tz',
              'venv.lib.python2.7.site-packages.dateutil.parser', 'venv.lib.python2.7.site-packages.dateutil.zoneinfo',
              'venv.lib.python2.7.site-packages.werkzeug', 'venv.lib.python2.7.site-packages.werkzeug.debug',
              'venv.lib.python2.7.site-packages.werkzeug.contrib', 'venv.lib.python2.7.site-packages.markupsafe',
              'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools._vendor',
              'venv.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.pkg_resources',
              'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.pip', 'venv.local.lib.python2.7.site-packages.pip._vendor',
              'venv.local.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.local.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.local.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.local.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.local.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.local.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.local.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.local.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.local.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.local.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.local.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.local.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.local.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.local.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.local.lib.python2.7.site-packages.pip._internal',
              'venv.local.lib.python2.7.site-packages.pip._internal.req',
              'venv.local.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.local.lib.python2.7.site-packages.pip._internal.utils',
              'venv.local.lib.python2.7.site-packages.pip._internal.models',
              'venv.local.lib.python2.7.site-packages.pip._internal.commands',
              'venv.local.lib.python2.7.site-packages.pip._internal.operations',
              'venv.local.lib.python2.7.site-packages.pytz', 'venv.local.lib.python2.7.site-packages.click',
              'venv.local.lib.python2.7.site-packages.flask', 'venv.local.lib.python2.7.site-packages.flask.ext',
              'venv.local.lib.python2.7.site-packages.numpy', 'venv.local.lib.python2.7.site-packages.numpy.ma',
              'venv.local.lib.python2.7.site-packages.numpy.ma.tests',
              'venv.local.lib.python2.7.site-packages.numpy.doc', 'venv.local.lib.python2.7.site-packages.numpy.fft',
              'venv.local.lib.python2.7.site-packages.numpy.fft.tests',
              'venv.local.lib.python2.7.site-packages.numpy.lib',
              'venv.local.lib.python2.7.site-packages.numpy.lib.tests',
              'venv.local.lib.python2.7.site-packages.numpy.core',
              'venv.local.lib.python2.7.site-packages.numpy.core.tests',
              'venv.local.lib.python2.7.site-packages.numpy.f2py',
              'venv.local.lib.python2.7.site-packages.numpy.f2py.tests',
              'venv.local.lib.python2.7.site-packages.numpy.tests',
              'venv.local.lib.python2.7.site-packages.numpy.compat',
              'venv.local.lib.python2.7.site-packages.numpy.linalg',
              'venv.local.lib.python2.7.site-packages.numpy.linalg.tests',
              'venv.local.lib.python2.7.site-packages.numpy.random',
              'venv.local.lib.python2.7.site-packages.numpy.random.tests',
              'venv.local.lib.python2.7.site-packages.numpy.testing',
              'venv.local.lib.python2.7.site-packages.numpy.testing.tests',
              'venv.local.lib.python2.7.site-packages.numpy.testing.nose_tools',
              'venv.local.lib.python2.7.site-packages.numpy.distutils',
              'venv.local.lib.python2.7.site-packages.numpy.distutils.tests',
              'venv.local.lib.python2.7.site-packages.numpy.distutils.command',
              'venv.local.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'venv.local.lib.python2.7.site-packages.numpy.matrixlib',
              'venv.local.lib.python2.7.site-packages.numpy.matrixlib.tests',
              'venv.local.lib.python2.7.site-packages.numpy.polynomial',
              'venv.local.lib.python2.7.site-packages.numpy.polynomial.tests',
              'venv.local.lib.python2.7.site-packages.scipy', 'venv.local.lib.python2.7.site-packages.scipy.io',
              'venv.local.lib.python2.7.site-packages.scipy.io.arff',
              'venv.local.lib.python2.7.site-packages.scipy.io.arff.tests',
              'venv.local.lib.python2.7.site-packages.scipy.io.tests',
              'venv.local.lib.python2.7.site-packages.scipy.io.matlab',
              'venv.local.lib.python2.7.site-packages.scipy.io.matlab.tests',
              'venv.local.lib.python2.7.site-packages.scipy.io.harwell_boeing',
              'venv.local.lib.python2.7.site-packages.scipy.io.harwell_boeing.tests',
              'venv.local.lib.python2.7.site-packages.scipy.odr',
              'venv.local.lib.python2.7.site-packages.scipy.odr.tests',
              'venv.local.lib.python2.7.site-packages.scipy._lib',
              'venv.local.lib.python2.7.site-packages.scipy._lib.tests',
              'venv.local.lib.python2.7.site-packages.scipy.misc',
              'venv.local.lib.python2.7.site-packages.scipy.misc.tests',
              'venv.local.lib.python2.7.site-packages.scipy.stats',
              'venv.local.lib.python2.7.site-packages.scipy.stats.tests',
              'venv.local.lib.python2.7.site-packages.scipy.linalg',
              'venv.local.lib.python2.7.site-packages.scipy.linalg.tests',
              'venv.local.lib.python2.7.site-packages.scipy.signal',
              'venv.local.lib.python2.7.site-packages.scipy.signal.tests',
              'venv.local.lib.python2.7.site-packages.scipy.sparse',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.tests',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.eigen',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.tests',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.dsolve',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.isolve',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.csgraph',
              'venv.local.lib.python2.7.site-packages.scipy.sparse.csgraph.tests',
              'venv.local.lib.python2.7.site-packages.scipy.cluster',
              'venv.local.lib.python2.7.site-packages.scipy.cluster.tests',
              'venv.local.lib.python2.7.site-packages.scipy.fftpack',
              'venv.local.lib.python2.7.site-packages.scipy.fftpack.tests',
              'venv.local.lib.python2.7.site-packages.scipy.ndimage',
              'venv.local.lib.python2.7.site-packages.scipy.ndimage.tests',
              'venv.local.lib.python2.7.site-packages.scipy.spatial',
              'venv.local.lib.python2.7.site-packages.scipy.spatial.tests',
              'venv.local.lib.python2.7.site-packages.scipy.special',
              'venv.local.lib.python2.7.site-packages.scipy.special.tests',
              'venv.local.lib.python2.7.site-packages.scipy.special._precompute',
              'venv.local.lib.python2.7.site-packages.scipy.optimize',
              'venv.local.lib.python2.7.site-packages.scipy.optimize._lsq',
              'venv.local.lib.python2.7.site-packages.scipy.optimize.tests',
              'venv.local.lib.python2.7.site-packages.scipy.optimize._trlib',
              'venv.local.lib.python2.7.site-packages.scipy.constants',
              'venv.local.lib.python2.7.site-packages.scipy.constants.tests',
              'venv.local.lib.python2.7.site-packages.scipy.integrate',
              'venv.local.lib.python2.7.site-packages.scipy.integrate._ivp',
              'venv.local.lib.python2.7.site-packages.scipy.integrate.tests',
              'venv.local.lib.python2.7.site-packages.scipy.interpolate',
              'venv.local.lib.python2.7.site-packages.scipy.interpolate.tests',
              'venv.local.lib.python2.7.site-packages.scipy._build_utils',
              'venv.local.lib.python2.7.site-packages.wheel', 'venv.local.lib.python2.7.site-packages.wheel.tool',
              'venv.local.lib.python2.7.site-packages.wheel.signatures',
              'venv.local.lib.python2.7.site-packages.jinja2', 'venv.local.lib.python2.7.site-packages.pandas',
              'venv.local.lib.python2.7.site-packages.pandas.io',
              'venv.local.lib.python2.7.site-packages.pandas.io.sas',
              'venv.local.lib.python2.7.site-packages.pandas.io.json',
              'venv.local.lib.python2.7.site-packages.pandas.io.formats',
              'venv.local.lib.python2.7.site-packages.pandas.io.msgpack',
              'venv.local.lib.python2.7.site-packages.pandas.io.clipboard',
              'venv.local.lib.python2.7.site-packages.pandas.api',
              'venv.local.lib.python2.7.site-packages.pandas.api.types',
              'venv.local.lib.python2.7.site-packages.pandas.core',
              'venv.local.lib.python2.7.site-packages.pandas.core.util',
              'venv.local.lib.python2.7.site-packages.pandas.core.tools',
              'venv.local.lib.python2.7.site-packages.pandas.core.dtypes',
              'venv.local.lib.python2.7.site-packages.pandas.core.sparse',
              'venv.local.lib.python2.7.site-packages.pandas.core.indexes',
              'venv.local.lib.python2.7.site-packages.pandas.core.reshape',
              'venv.local.lib.python2.7.site-packages.pandas.core.computation',
              'venv.local.lib.python2.7.site-packages.pandas.util',
              'venv.local.lib.python2.7.site-packages.pandas._libs',
              'venv.local.lib.python2.7.site-packages.pandas._libs.tslibs',
              'venv.local.lib.python2.7.site-packages.pandas.stats',
              'venv.local.lib.python2.7.site-packages.pandas.tests',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.sas',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.json',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.parser',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.formats',
              'venv.local.lib.python2.7.site-packages.pandas.tests.io.msgpack',
              'venv.local.lib.python2.7.site-packages.pandas.tests.api',
              'venv.local.lib.python2.7.site-packages.pandas.tests.util',
              'venv.local.lib.python2.7.site-packages.pandas.tests.frame',
              'venv.local.lib.python2.7.site-packages.pandas.tests.tools',
              'venv.local.lib.python2.7.site-packages.pandas.tests.dtypes',
              'venv.local.lib.python2.7.site-packages.pandas.tests.scalar',
              'venv.local.lib.python2.7.site-packages.pandas.tests.series',
              'venv.local.lib.python2.7.site-packages.pandas.tests.sparse',
              'venv.local.lib.python2.7.site-packages.pandas.tests.groupby',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes.period',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.local.lib.python2.7.site-packages.pandas.tests.reshape',
              'venv.local.lib.python2.7.site-packages.pandas.tests.tseries',
              'venv.local.lib.python2.7.site-packages.pandas.tests.indexing',
              'venv.local.lib.python2.7.site-packages.pandas.tests.plotting',
              'venv.local.lib.python2.7.site-packages.pandas.tests.internals',
              'venv.local.lib.python2.7.site-packages.pandas.tests.computation',
              'venv.local.lib.python2.7.site-packages.pandas.tools',
              'venv.local.lib.python2.7.site-packages.pandas.types',
              'venv.local.lib.python2.7.site-packages.pandas.compat',
              'venv.local.lib.python2.7.site-packages.pandas.compat.numpy',
              'venv.local.lib.python2.7.site-packages.pandas.errors',
              'venv.local.lib.python2.7.site-packages.pandas.formats',
              'venv.local.lib.python2.7.site-packages.pandas.tseries',
              'venv.local.lib.python2.7.site-packages.pandas.plotting',
              'venv.local.lib.python2.7.site-packages.pandas.computation',
              'venv.local.lib.python2.7.site-packages.sklearn', 'venv.local.lib.python2.7.site-packages.sklearn.svm',
              'venv.local.lib.python2.7.site-packages.sklearn.svm.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.tree',
              'venv.local.lib.python2.7.site-packages.sklearn.tree.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.utils',
              'venv.local.lib.python2.7.site-packages.sklearn.utils.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.utils.sparsetools',
              'venv.local.lib.python2.7.site-packages.sklearn.utils.sparsetools.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.cluster',
              'venv.local.lib.python2.7.site-packages.sklearn.cluster.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.metrics',
              'venv.local.lib.python2.7.site-packages.sklearn.metrics.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.metrics.cluster',
              'venv.local.lib.python2.7.site-packages.sklearn.metrics.cluster.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.mixture',
              'venv.local.lib.python2.7.site-packages.sklearn.mixture.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.datasets',
              'venv.local.lib.python2.7.site-packages.sklearn.datasets.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.ensemble',
              'venv.local.lib.python2.7.site-packages.sklearn.ensemble.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.manifold',
              'venv.local.lib.python2.7.site-packages.sklearn.manifold.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.externals',
              'venv.local.lib.python2.7.site-packages.sklearn.externals.joblib',
              'venv.local.lib.python2.7.site-packages.sklearn.neighbors',
              'venv.local.lib.python2.7.site-packages.sklearn.neighbors.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.covariance',
              'venv.local.lib.python2.7.site-packages.sklearn.covariance.tests',
              'venv.local.lib.python2.7.site-packages.sklearn._build_utils',
              'venv.local.lib.python2.7.site-packages.sklearn.linear_model',
              'venv.local.lib.python2.7.site-packages.sklearn.linear_model.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.__check_build',
              'venv.local.lib.python2.7.site-packages.sklearn.decomposition',
              'venv.local.lib.python2.7.site-packages.sklearn.decomposition.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.preprocessing',
              'venv.local.lib.python2.7.site-packages.sklearn.preprocessing.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.neural_network',
              'venv.local.lib.python2.7.site-packages.sklearn.neural_network.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.model_selection',
              'venv.local.lib.python2.7.site-packages.sklearn.model_selection.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.semi_supervised',
              'venv.local.lib.python2.7.site-packages.sklearn.semi_supervised.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.gaussian_process',
              'venv.local.lib.python2.7.site-packages.sklearn.gaussian_process.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.feature_selection',
              'venv.local.lib.python2.7.site-packages.sklearn.feature_selection.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.feature_extraction',
              'venv.local.lib.python2.7.site-packages.sklearn.feature_extraction.tests',
              'venv.local.lib.python2.7.site-packages.sklearn.cross_decomposition',
              'venv.local.lib.python2.7.site-packages.sklearn.cross_decomposition.tests',
              'venv.local.lib.python2.7.site-packages.dateutil', 'venv.local.lib.python2.7.site-packages.dateutil.tz',
              'venv.local.lib.python2.7.site-packages.dateutil.parser',
              'venv.local.lib.python2.7.site-packages.dateutil.zoneinfo',
              'venv.local.lib.python2.7.site-packages.werkzeug',
              'venv.local.lib.python2.7.site-packages.werkzeug.debug',
              'venv.local.lib.python2.7.site-packages.werkzeug.contrib',
              'venv.local.lib.python2.7.site-packages.markupsafe', 'venv.local.lib.python2.7.site-packages.setuptools',
              'venv.local.lib.python2.7.site-packages.setuptools.extern',
              'venv.local.lib.python2.7.site-packages.setuptools._vendor',
              'venv.local.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.setuptools.command',
              'venv.local.lib.python2.7.site-packages.pkg_resources',
              'venv.local.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.local.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.local.lib.python2.7.site-packages.pkg_resources._vendor.packaging', 'JobFinder', 'JobFinder.Models',
              'JobFinder.Controllers'],
    url='https://github.com/CowboardKeyboys/HFS2018.git',
    license='Apache License',
    author='MaxAndersson',
    author_email='maxn90 (at) gmail.com ',
    description='Finds best suited municipality in Sweden based on your job profile'
)
